### ISSUE TITLE
datasus package

### ISSUE THREAD

**Issue by QooModa** [danicat/pysus#3]
Hello!
Thank you for this great project. It is quite helpful.

I writing the code exactly as you suggested in

from datasus import read_dbc

But I don't know where to get this datasus module.

Is it inside another package?

Thank you so much!

**Comment by mymatsubara** [comment]
@QooModa you first need to build the project running the following command (might only work on linux tho):

```
make install
```

After that, you'll have the module installed on your machine.

Another option is to use other packages such as [datasus-dbc](https://github.com/mymatsubara/datasus-dbc-py) (my shameless plug 😅) which might work with most platforms and is installable via pip (`pip install datasus-dbc`).
